lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    public_key_path: '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 604800 # One Day
    user_identity_field: id
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:
            enabled: false
            name:    BEARER
        query_parameter:
            enabled: true
            name:    token
