security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        jwt:
            lexik_jwt:
              class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            anonymous: true

        main:
            pattern:   ^/api
            anonymous: false
            stateless: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
      -
        path: ^/login
        roles:
          - IS_AUTHENTICATED_ANONYMOUSLY
      -
        path: ^/api
        roles:
          - ROLE_STAFF
