matrix:
  include:
    -
      language: php
      php: 7.1
      install:
          - composer install
      script:
          - composer test
    -
      language: node_js
      node_js: 8
branches:
    only:
        - master
