version: '3.0'
services:
  ingress:
    build: ./
    image: wikimedia/takedown-tools-ingress
    env_file:
      - .env
    links:
      - web
      - api
  web:
    build: ./client
    image: wikimedia/takedown-tools-web
    env_file:
      - .env
    links:
      - api
  api:
    build: ./server
    image: wikimedia/takedown-tools-api
    env_file:
      - .env
    links:
      - database
    volumes:
     - .:/var/www:cached
  database:
    image: 'mariadb:10.2'
    env_file:
     - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
