version: '2'
services:
  web:
    build: ./
    env_file:
      - .env
    links:
      - database
    volumes:
     - .:/var/www:cached
  database:
    image: 'mariadb:10.2'
    env_file:
     - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - database:/var/lib/mysql
  composer:
    image: 'composer'
    command: 'composer install'
    volumes:
     - .:/app:cached
  node:
    image: 'node:8'
    env_file:
     - .env
    command: ./bin/node-start
    working_dir: /code
    volumes:
     - .:/code:cached
volumes:
  database:
