index:
   path: /
   defaults:
     _controller: 'App\Controller\AuthController::loginAction'
   methods: ['GET']

token:
   path: /token
   defaults:
     _controller: 'App\Controller\AuthController::tokenAction'
   methods: ['GET']

# Depends on sensio/framework-extra-bundle:^3.0 and doctrine/annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
