index:
   path: /
   defaults:
     _controller: 'App\Controller\AuthController::loginAction'
     _format: 'html'
   methods: ['GET']

token:
   path: /token
   defaults:
     _controller: 'App\Controller\AuthController::tokenAction'
     _format: 'json'
   methods: ['GET']

takedown:
   path: /takedown
   defaults:
     _controller: 'App\Controller\LegalTakedownController::createAction'
     _format: 'json'
   methods: ['POST']

# Depends on sensio/framework-extra-bundle:^3.0 and doctrine/annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
