# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  app.cache:
    class: Symfony\Component\Cache\Simple\FilesystemCache
    arguments:
      - 'app'
      - 0
      - '%kernel.cache_dir%'

  app.oauth_consumer:
    class: MediaWiki\OAuthClient\Consumer
    arguments:
      - '%env(OAUTH_CONSUMER_KEY)%'
      - '%env(OAUTH_CONSUMER_SECRET)%'

  app.oauth_client_config:
    class: MediaWiki\OAuthClient\ClientConfig
    arguments:
      - '%env(OAUTH_ENDPOINT)%'
    calls:
      - [setConsumer, ['@app.oauth_consumer']]

  app.oauth_client:
    class: MediaWiki\OAuthClient\Client
    arguments:
      - '@app.oauth_client_config'
    calls:
      - [setCallback, ["@=service('request_stack').getMasterRequest().getUriForPath('/login')"]]

  app.handler_stack_factory:
    class: App\Client\HandlerStackFactory
    arguments:
      - '@security.token_storage'
      - '%env(OAUTH_CONSUMER_KEY)%'
      - '%env(OAUTH_CONSUMER_SECRET)%'

  app.handler_stack:
    class: GuzzleHttp\HandlerStack
    factory: ['@app.handler_stack_factory', 'createHandlerStack']

  app.mediawiki_client_guzzle:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: '%env(MEDIAWIKI_API_URL)%'
        handler: '@app.handler_stack'

  app.mediawiki_client:
    class: App\Client\MediaWikiClient
    arguments:
      - '@app.mediawiki_client_guzzle'
      - '@serializer'
      - '%kernel.environment%'

  app.event.jwt_created_listener:
      class: App\EventListener\JWTCreatedEventListener
      arguments:
        - '@serializer'
      tags:
          -
            name: kernel.event_listener
            event: lexik_jwt_authentication.on_jwt_created
            method: onJWTCreated

  app.controller_auth:
    class: App\Controller\AuthController
    arguments:
      - '@app.cache'
      - '@app.mediawiki_client'
      - '@app.oauth_client'
      - '@security.token_storage'
      - '@lexik_jwt_authentication.jwt_manager'
      - '@doctrine'

  app.controller_takedown:
    class: App\Controller\TakedownController
    arguments:
      - '@doctrine'
      - '@serializer'
      - '@app.mediawiki_client'
      - '@entity_attacher'

  app.controller_user:
    class: App\Controller\UserController
    arguments:
      - '@doctrine'
      - '@serializer'
      - '@app.mediawiki_client'

  app.extension_guesser:
    class: Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser
    factory: ['Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser', getInstance]

  app.controller_file:
    class: App\Controller\FileController
    arguments:
      - '@filesystem'
      - '@app.extension_guesser'
      - '@doctrine'
      - '%kernel.project_dir%'

  app.return_listener:
    class: GeoSocio\SerializeResponse\EventListener\KernelViewListener
    arguments:
        - '@serializer'
        - '@serializer'
        - '@security.token_storage'
        # Default Groups
        -
          - 'api'
    tags:
        - { name: kernel.event_listener, event: kernel.view }

  app.serializer_global_user_info:
      class: App\Serializer\GlobalUserInfoDenormalizer
      public: false
      tags:
        - { name: serializer.normalizer }


  app.serializer_site_matrix:
      class: App\Serializer\SiteMatrixDenormalizer
      public: false
      tags:
        - { name: serializer.normalizer }
