# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'en'
  app.files_dir: '%kernel.project_dir%/var/files'
  app.organization:
    name: 'Wikimedia Foundation'
    address:
      - '1 Montgomery Street'
      - 'Suite 1600'
    city: 'San Francisco'
    state: 'CA'
    zip: 94104
    country: 'US'
    phone: '+1-415-839-6885'
  app.contact:
    name:
      first: '%env(CONTACT_FIRST_NAME)%'
      last: '%env(CONTACT_LAST_NAME)%'
    email: '%env(CONTACT_EMAIL)%'
    phone: '%env(CONTACT_PHONE)%'

services:
  app.cache:
    class: Symfony\Component\Cache\Simple\FilesystemCache
    arguments:
      - 'app'
      - 0
      - '%kernel.cache_dir%'

  app.oauth_consumer:
    class: MediaWiki\OAuthClient\Consumer
    arguments:
      - '%env(OAUTH_CONSUMER_KEY)%'
      - '%env(OAUTH_CONSUMER_SECRET)%'

  app.oauth_client_config:
    class: MediaWiki\OAuthClient\ClientConfig
    arguments:
      - 'https://meta.wikimedia.org/w/index.php?title=Special:OAuth'
    calls:
      - [setConsumer, ['@app.oauth_consumer']]

  app.oauth_client:
    class: MediaWiki\OAuthClient\Client
    arguments:
      - '@app.oauth_client_config'
    calls:
      - [setCallback, ["@=service('request_stack').getMasterRequest().getUriForPath('/login')"]]

  app.handler_stack_factory:
    class: App\Client\HandlerStackFactory
    arguments:
      - '@security.token_storage'
      - '%env(OAUTH_CONSUMER_KEY)%'
      - '%env(OAUTH_CONSUMER_SECRET)%'

  app.handler_stack:
    class: GuzzleHttp\HandlerStack
    factory: ['@app.handler_stack_factory', 'createHandlerStack']

  app.mediawiki_client_guzzle:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: 'https://meta.wikimedia.org/w/api.php'
        handler: '@app.handler_stack'

  app.mediawiki_client:
    class: App\Client\MediaWikiClient
    arguments:
      - '@app.mediawiki_client_guzzle'
      - '@serializer'
      - '@serializer'
      - '@serializer'
      - '%kernel.environment%'

  app.event.jwt_created_listener:
      class: App\EventListener\JWTCreatedEventListener
      arguments:
        - '@serializer'
      tags:
          -
            name: kernel.event_listener
            event: lexik_jwt_authentication.on_jwt_created
            method: onJWTCreated

  app.controller_auth:
    class: App\Controller\AuthController
    arguments:
      - '@app.cache'
      - '@app.mediawiki_client'
      - '@app.oauth_client'
      - '@security.token_storage'
      - '@lexik_jwt_authentication.jwt_manager'
      - '@doctrine'

  app.controller_takedown:
    class: App\Controller\TakedownController
    arguments:
      - '@doctrine'
      - '@app.mediawiki_client'
      - '@entity_attacher'
      - '@app.lumen_client'
      - '@app.ncmec_client'
      - '@security.token_storage'

  app.controller_user:
    class: App\Controller\UserController
    arguments:
      - '@doctrine'
      - '@serializer'
      - '@app.mediawiki_client'

  app.extension_guesser:
    class: Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser
    factory: ['Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser', getInstance]

  app.controller_file:
    class: App\Controller\FileController
    arguments:
      - '@filesystem'
      - '@app.extension_guesser'
      - '@doctrine'
      - '%app.files_dir%'

  # @TODO Remove this when bundle becomes available.
  app.group_loader:
    class: GeoSocio\HttpSerializer\Loader\GroupLoader
    arguments:
      - '@controller_resolver'
      - '@annotation_reader'


  # @TODO Remove this when bundle becomes available.
  app.return_listener:
    class: GeoSocio\HttpSerializer\EventListener\KernelViewListener
    arguments:
        - '@serializer'
        - '@serializer'
        - '@serializer'
        - '@app.group_loader'
        - '@event_dispatcher'
    tags:
        - { name: kernel.event_listener, event: kernel.view }

  # @TODO Remove this when bundle becomes available.
  app.exception_listener:
    class: GeoSocio\HttpSerializer\EventListener\KernelExceptionListener
    arguments:
        - '@serializer'
        - '@serializer'
        - '@serializer'
        - '@event_dispatcher'
        - 'json'
    tags:
        - { name: kernel.event_listener, event: kernel.exception }

  # @TODO Remove this when bundle becomes available.
  app.serializer_exception:
      class: GeoSocio\HttpSerializer\Serializer\ExceptionNormalizer
      arguments:
          - '%kernel.environment%'
      public: false
      tags:
        - { name: serializer.normalizer }

  # @TODO Remove this when bundle becomes available.
  app.serializer_constraint:
      class: GeoSocio\HttpSerializer\Serializer\ConstraintViolationNormalizer
      public: false
      tags:
        - { name: serializer.normalizer }

  # @TODO Remove this when bundle becomes available.
  app.content_class_resolver:
      class: GeoSocio\HttpSerializer\ArgumentResolver\ContentClassResolver
      arguments:
        - '@serializer'
        - '@serializer'
        - '@serializer'
        - '@app.group_loader'
        - '@event_dispatcher'
        - '@validator'
      public: false
      tags:
        - { name: controller.argument_value_resolver, priority: 0 }


  app.serializer_global_user_info:
      class: App\Serializer\GlobalUserInfoDenormalizer
      public: false
      tags:
        - { name: serializer.normalizer }


  app.serializer_site_matrix:
      class: App\Serializer\SiteMatrixDenormalizer
      public: false
      tags:
        - { name: serializer.normalizer }

  app.serializer_lumen:
      class: App\Serializer\LumenNormalizer
      arguments:
        - '%app.organization%'
      public: false
      tags:
        - { name: serializer.normalizer }

  app.lumen_client_guzzle:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: "@=parameter('kernel.environment') === 'prod' ? 'https://lumendatabase.org' : 'https://api-beta.lumendatabase.org'"
        headers:
          X-Authentication-Token: '%env(LUMEN_AUTH_TOKEN)%'
          Accept: 'application/json'
          User-Agent: 'WikiMediaLumenBot/1.0'

  app.lumen_client:
    class: App\Client\LumenClient
    arguments:
      - '@app.lumen_client_guzzle'
      - '@app.mediawiki_client'
      - '@serializer'
      - '%app.files_dir%'

  app.ncmec_client_guzzle:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: "@=parameter('kernel.environment') === 'prod' ? 'https://report.cybertip.org/ispws/' : 'https://exttest.cybertip.org/ispws/'"
        headers:
          Accept: 'text/xml'
        auth:
          - '%env(NCMEC_USER)%'
          - '%env(NCMEC_PASS)%'

  app.ncmec_client:
    class: App\Client\NcmecClient
    arguments:
      - '@app.ncmec_client_guzzle'
      - '@app.mediawiki_client'
      - '@serializer'
      - '@serializer'
      - '@serializer'

  app.serializer_ncmec:
      class: App\Serializer\NcmecNormalizer
      arguments:
        - '%app.organization%'
        - '%app.contact%'
      public: false
      tags:
        - { name: serializer.normalizer }
